# Generated by Django 5.0 on 2023-12-23 08:35

from django.db import migrations, models
import secrets

def set_default_values(apps, schema_editor):
    CustomUser = apps.get_model('core', 'CustomUser')
    for user in CustomUser.objects.all():
        user.confirmation_token = secrets.token_urlsafe(30)
        user.email_confirmed = False
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_default_values),
    ]
