# Generated by Django 5.0 on 2023-12-23 15:22

from django.db import migrations, models

def set_default_values(apps, schema_editor):
    Payment = apps.get_model('api', 'Payment')
    for payment in Payment.objects.all():
            if payment.receipt_url is None:
                payment.receipt_url = 'https://shopit-receipt-url'
            payment.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(set_default_values),
    ]
